### ISSUE TITLE
ID2. Creation of the module

### ISSUE THREAD

**Issue by paarals** [ConsorciAOC-PRJ/decidim-module-trusted-ids#1]
**Is the new functionality related to an issue? describe it**
Currently, there are several modules that participate in idcat mobile/valid and the Via Oberta This means that it is not easy to find and install it.

**Describe the solution you would like (initial requirement)**
Integration of the different modules into one for easy installation:
- https://github.com/gencat/decidim-module-idcat_mobil
- https://github.com/gencat/omniauth-idcat_mobil
- https://github.com/ConsorciAOC/Decidim-Catalunya/tree/main/decidim-via_oberta_authorization

This module should be understood as an authenticator of identities that has two phases: a first phase of authenticator of identities and a second phase of verifier of identities for their participation. It is hoped that it can be scaled to other national, state and international identity systems that wish to comply with this flow.

**Acceptance Criteria**
- [x] Fork of the IdCat Mobil module
- [x] Scale of the new module
- [x] Review the current code
- [x] Crowdin translation project
- [x] Codecov badges
- [x] Codeclimate badges
- [x] Tests badges
- [x] Placeholder module options with attr_accessor
- [x] make test_app and development_app work
- [ ] ~In the documentation phase, some recommendations are specified to be incorporated into the terms and conditions that incorporate this module, specifying which personal data is saved and under which conditions (encrypted)~

**Technical specification**

**Technical solution**

**Mock up (if needed)**
Flow chart:
![Image](https://user-images.githubusercontent.com/40388743/228882693-8b93a59e-4955-4bb5-a20a-65d50948c18e.png)

**Step by step through the test**

**Additional Context**
Currently, it will be possible to authenticate the Catalan identity system through the Valid and Via Oberta.

**Comment by microstudi** [comment]
Crowdin: https://crowdin.com/project/decidim-trusted-ids
